### ISSUE TITLE
Check if file was already swarmed before submitting again.

### ISSUE THREAD

**Issue by mrtizmoatwork** [polyswarm/autopsy-module#16]
If a user submits a file to be Swarmed, but the file was previously submitted in the same case, don't submit it again. Display a pop-up window telling the user that they already submitted that file.

This will prevent them from seeing the sqlite db constraint violation exception on multi-submit.

This will prevent them from seeing duplicate attributes added to files in the PolySwarm Results results.

**Comment by Rizato** [comment]
We should also have a way to force rerun to work with https://github.com/polyswarm/consumer/issues/7.

**Comment by mrtizmoatwork** [comment]
82da58d adds check for existing pending submission and does not submit if one exists. This is the first step.
