### ISSUE TITLE
Swarming Status Indicator

### ISSUE THREAD

**Issue by myhndl** [polyswarm/autopsy-module#27]
**Is your feature request related to a problem? Please describe.**
There's nothing to indicate that a scan is in progress, user might be confused as to whether it's working and results are incoming.

**Describe the solution you'd like**
Autopsy doesn't allow modules to edit or delete existing file attributes, so we can't go that route.

Can be we use the status bar at the bottom?

**Comment by mrtizmoatwork** [comment]
Yes. When new processes are started, they can append a process status indicator to the list of running processes displayed in the bottom right.
